In [200]:
import pandas as pd

train_data = pd.read_csv('data/train.csv')
test_data = pd.read_csv('data/test.csv')


1. 성별, 클라스- 생존율
2. 가족(SibSp,Parch), 성별 생존율

In [352]:
features = ['Pclass', 'Sex', 'Cabin', 'Family']
train_input = pd.get_dummies(train_data[features]) # get_dummies 글자로 된 데이터 숫자로 표현
test_input = pd.get_dummies(test_data[features])
train_input.head()

Pclass  Cabin  Family  Sex_female  Sex_male
0       3  False       1       False      True
1       1  False       1        True     False
2       3  False       0        True     False
3       1  False       1        True     False
4       3  False       0       False      True

In [321]:
cabin_null = train_data[['Cabin']].isnull()
train_data['Cabin'] = cabin_null
cabin_null_t = test_data[['Cabin']].isnull()
test_data['Cabin'] = cabin_null_t


In [322]:
train_data['Family'] = train_data['SibSp'] + train_data['Parch']
test_data['Family'] = test_data['SibSp'] + test_data['Parch']
train_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare  Cabin Embarked  Family  
0      0         A/5 21171   7.2500  False        S       1  
1      0          PC 17599  71.2833  False        C       1  
2      0  STON/O2. 3101282   7.9250  False        S       0  
3      0            113803  53.1000  False        S       1  
4      0            373450   8.0500  False        S       0

In [328]:
from sklearn.ensemble import RandomForestClassifier

In [329]:
rfc = RandomForestClassifier()

In [330]:
train_target = train_data[['Survived']]


In [331]:
rfc.fit(train_input, train_target)

C:\Users\2-12\Desktop\DMF\ML\venv\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier()

In [332]:
rfc.feature_importances_

array([0.13158085, 0.3959522 , 0.10808581, 0.20236812, 0.16201303])

In [333]:
from sklearn.model_selection import cross_validate

In [334]:
scores = cross_validate(rfc, train_input, train_target, n_jobs=-1)

In [335]:
scores

{'fit_time': array([0.21753311, 0.20915294, 0.21131253, 0.20501399, 0.20326686]),
 'score_time': array([0.01748133, 0.01041555, 0.00974178, 0.00788379, 0.00770998]),
 'test_score': array([0.7877095 , 0.82022472, 0.83707865, 0.80898876, 0.82022472])}

In [336]:
predictions = rfc.predict(test_input)

In [337]:
result = {
    'PassengerId': test_data['PassengerId'],
    'Survived': predictions,
}
output = pd.DataFrame(result)


In [338]:
output.to_csv('my_submission.csv', index=False)

# 그리드서치

In [342]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

In [343]:
params = {
   'min_impurity_decrease': np.arange(0.0001, 0.001, 0.0001),
    'max_depth': range(5, 20, 1),
    'min_samples_split': range(2, 100, 10),
}


In [344]:
dt = DecisionTreeClassifier(max_depth=5,
                       min_impurity_decrease=np.float64(0.0009000000000000001),
                       min_samples_split=12)
# gs = GridSearchCV(dt, params, n_jobs=-1)

In [345]:
dt.fit(train_input, train_target)

DecisionTreeClassifier(max_depth=5,
                       min_impurity_decrease=np.float64(0.0009000000000000001),
                       min_samples_split=12)

In [346]:
gs.best_estimator_

DecisionTreeClassifier(max_depth=26,
                       min_impurity_decrease=np.float64(0.0008965429868602329),
                       min_samples_leaf=15, min_samples_split=12)

In [347]:
gs.cv_results_['mean_test_score']

array([0.79914004, 0.79464566, 0.79465194, 0.79239847, 0.79914004,
       0.79465194, 0.79464566, 0.79464566, 0.79464566, 0.79127487,
       0.79464566, 0.79914004, 0.79465194, 0.79239847, 0.79914004,
       0.79239847, 0.79689913, 0.79689285, 0.79464566, 0.79239847,
       0.79239847, 0.79464566, 0.79464566, 0.79801645, 0.79464566,
       0.79689285, 0.79463938, 0.79464566, 0.79352206, 0.79465194,
       0.79689913, 0.79464566, 0.79689913, 0.79239847, 0.79239847,
       0.79127487, 0.79464566, 0.79239847, 0.79914004, 0.79464566,
       0.79464566, 0.79576298, 0.79801645, 0.79239847, 0.79464566,
       0.79465194, 0.79465194, 0.79914004, 0.79127487, 0.79465194,
       0.79576925, 0.79463938, 0.79689913, 0.79689913, 0.79914004,
       0.79352206, 0.79914004, 0.79239847, 0.79914004, 0.79914004,
       0.79351579, 0.79914004, 0.79914004, 0.79464566, 0.79801645,
       0.79914004, 0.79689913, 0.79914004, 0.79689913, 0.79914004,
       0.79801645, 0.78904651, 0.79689913, 0.79576925, 0.79465

In [353]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(n_estimators=1000, learning_rate=0.1) # n_estimators=나무의 개수, learning_rate=학습률  두 옵션은 반비례로 줘야함
scores = cross_validate(gb, train_input, train_target, return_train_score=True, n_jobs=-1)
scores

{'fit_time': array([1.0726831 , 1.16625309, 1.07899475, 1.08699584, 1.14925432]),
 'score_time': array([0.00731349, 0.00699997, 0.00800014, 0.00625849, 0.00700021]),
 'test_score': array([0.75418994, 0.81460674, 0.80337079, 0.76404494, 0.79775281]),
 'train_score': array([0.81601124, 0.81346424, 0.81346424, 0.82187938, 0.81486676])}

In [354]:
gb.fit(train_input, train_target)

C:\Users\2-12\Desktop\DMF\ML\venv\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingClassifier(n_estimators=1000)

In [355]:
predictions = gb.predict(test_input)
result = {
    'PassengerId': test_data['PassengerId'],
    'Survived': predictions,
}
output = pd.DataFrame(result)
output.to_csv('my_submission9.csv', index=False)


In [356]:
predictions

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [304]:
from scipy.stats import uniform, randint

In [305]:
rgen = randint(0, 10)
np.unique(rgen.rvs(1000), return_counts=True) 

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 91,  99, 107,  97,  86, 120, 104,  99, 103,  94]))

In [306]:
params = {
    'min_impurity_decrease': uniform(0.0001, 0.001),
    'max_depth': randint(20, 50),
    'min_samples_split': randint(2, 25),
    'min_samples_leaf': randint(1, 25),
}

In [307]:
from sklearn.model_selection import RandomizedSearchCV
gs = RandomizedSearchCV(dt, params, n_iter=100, n_jobs=-1, random_state=42) #n_iter 랜덤한 숫자를 얼마나 반복할지
gs.fit(train_input, train_target)

RandomizedSearchCV(estimator=DecisionTreeClassifier(max_depth=5,
                                                    min_impurity_decrease=np.float64(0.0009000000000000001),
                                                    min_samples_split=12),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x00000150FF556720>,
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x00000150FF557230>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x00000150FF554320>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x00000150FF557BF0>},
                   random_state=42)

In [308]:
gs.best_estimator_

DecisionTreeClassifier(max_depth=26,
                       min_impurity_decrease=np.float64(0.0008965429868602329),
                       min_samples_leaf=15, min_samples_split=12)

In [309]:
dtc = DecisionTreeClassifier(max_depth=26,
                       min_impurity_decrease=np.float64(0.0008965429868602329),
                       min_samples_leaf=15, min_samples_split=12,
                       random_state=42)

In [310]:
dtc.fit(train_input, train_target)

DecisionTreeClassifier(max_depth=26,
                       min_impurity_decrease=np.float64(0.0008965429868602329),
                       min_samples_leaf=15, min_samples_split=12,
                       random_state=42)

In [311]:
predictions = dtc.predict(test_input)
result = {
    'PassengerId': test_data['PassengerId'],
    'Survived': predictions,
}
output = pd.DataFrame(result)
output.to_csv('my_submission8.csv', index=False)

In [312]:
predictions

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,